---

# install needed packages
- name: Install required packages CentOS family
  yum:
    name: "{{ item }}"
    state: "installed"
  with_items:
    - "{{ installCentos }}"
  when:
    - ansible_facts['distribution'] == 'CentOS'
    - '"item" != ansible_facts.packages'
