---

- name: Cron | Gather server Package information
  package_facts:
    manager: "auto"

- name: Cron | Include OS variables
  include_vars: '{{ ansible_os_family }}.yml'

- name: Cron | Include OS installation
  include_tasks: '{{ ansible_os_family }}.yml'
