---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/default/yaml-lint.yml
platforms:
  - name: instance
    image: "ggiinnoo/docker-ansible/${DOCKER_IMAGE}:latest"
    registry:
      url: docker.pkg.github.com
    privileged: true
    pre_build_image: true
    groups:
      - webservers
      - dbservers
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-playbook.yml}
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
