---

- name: Cron | Redhat | Install required packages
  yum:
    name: "{{ item }}"
    state: "installed"
  with_items:
    - "{{ installCentos }}"
  when:
    - '"item" != ansible_facts.packages'
  loop_control:
    label: "Installing package: {{ item }}"
