---
name: Ansible role cron

on: push

jobs:
  build:
    name: Build for centos
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        centos: [6, 7]
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Installing prerequisites
        run: sudo apt-get install -y python-pip libssl-dev ya
      - name: install required modules
        run: pip install --upgrade --user setuptools && pip install --user molecule docker yamllint
      - name: run molecule
        run: python -m molecule test
