---
name: Ansible role cron

on:
  push:
    branches:
     -  'release/**'

jobs:
  build:
    name: Build for centos
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        centos: ['centos6', 'centos7']
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Set up Python 2.7
        uses: actions/setup-python@v1
        with:
          python-version: 2.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yamllint molecule docker ansible-lint
      - name: DEBUG
        env:
          MATRIX_CONTEXT: ${{ matrix }}
        run: echo "$MATRIX_CONTEXT"
      # - name: run molecule
      #   run: molecule test