---
name: Ansible role cron

on:
  push:
    branches:
     -  'release/**'

jobs:
  build:
    name: Build for centos
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        centos: [6, 7]
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Installing prerequisites
        run: sudo apt-get install -y python-pip libssl-dev flake8 python3-venv
      - run: python -m pip install wheel
      - run: python -m pip install yamllint && yamllint -v
      - name: installing required python modules
        run: python3 -m pip install --upgrade setuptools && python3 -m pip install molecule docker ansible-lint
      - name: run molecule
        run: molecule --debug test
