---
name: Ansible role cron

on: push

jobs:
  build:
    name: Build for centos
    runs-on: ubuntu-latest
    strategy:
      matrix:
        centos: [6, 7]
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: install preq
        run: sudo apt-get install gcc python-pip python-vagrant libssl-dev libffi-dev
      - name: install wheel
        run: pip install wheel
      - name: install required modules
        run: pip install molecule docker
      - name: pip
        run: pip list && pip --version
      - name: ansible and docker version
        run: ansible --version && docker -v
      - name: run molecule
        run: /home/runner/.local/lib/python2.7/site-packages/molecule test
