---
name: Ansible role cron

on: push

jobs:
  build:
    name: Build for centos
    runs-on: ubuntu-latest
    strategy:
      matrix:
        centos: [6, 7]
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: install wheel
        run: pip install wheel
      - name: run molecule
        run: molecule test
      - name: install required modules
        run: pip install molecule docker
      - name: install mlocate
        run: apt install mlocate && updatedb && locate molecule
      - name: run molecule
        run: molecule test
